name: Deploy Databricks Job

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: pip install --upgrade databricks-cli

      - name: Set Databricks environment
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: List files in mlops/jobs
        run: ls -la mlops/jobs

      - name: Substitute cluster_id in JSON
        run: |
          CLUSTER_ID="${{ secrets.EXISTING_CLUSTER_ID }}"
          sed "s|{{CLUSTER_ID}}|$CLUSTER_ID|g" mlops/jobs/job_config.json.template > mlops/jobs/predict_job_config.json

      - name: Check JSON content
        run: cat mlops/jobs/predict_job_config.json

      - name: Create or update Databricks job
        run: |
          databricks jobs create --json @mlops/jobs/predict_job_config.json || \
          (echo "Job already exists, updating..." && databricks jobs reset --json @mlops/jobs/predict_job_config.json)
